name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to Railway
        run: |
          npx railway@latest up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          API_HASH: ${{ secrets.API_HASH }}
          API_ID: ${{ secrets.API_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          LOG_CHANNEL: ${{ secrets.LOG_CHANNEL }}
          MULTI_TOKEN1: ${{ secrets.MULTI_TOKEN1 }}
          MULTI_TOKEN2: ${{ secrets.MULTI_TOKEN2 }}
          MULTI_TOKEN3: ${{ secrets.MULTI_TOKEN3 }}
          MULTI_TOKEN4: ${{ secrets.MULTI_TOKEN4 }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
